---
title: "Output"
---


# Project publications
*More coming soon ... *

* Kreuder-Sonnen, C. and C. Rauh (2024) 'Capturing and comparing transboundary crises: a text-as-data measurement model', *Conference Paper*, 29th DVPW Congress, Georg-August Universität Göttingen, 24.-27.09.2024.
<br>
<br>

::: {style="color: gray;"}
# Related prior team publications


* Kreuder-Sonnen, C. and Zangl, B. (2024) [‘The politics of IO authority transfers: explaining informal internationalisation and unilateral renationalisation’](https://www.tandfonline.com/doi/full/10.1080/13501763.2024.2325008), *Journal of European Public Policy* 32(4).

* Kreuder-Sonnen, C. and Tantow, P.M. (2023) [‘Crisis and Change at IOM: Critical Juncture, Precedents, and Task Expansion’](https://www.cambridge.org/core/books/iom-unbound/crisis-and-change-at-iom/D0947AAE807BA8C326340A129AD202C7), in C. Costello, M. Bradley and A. Sherwood (eds), IOM Unbound? Obligations and Accountability of the International Organization for Migration in an Era of Expansion, Cambridge: *Cambridge University Press*, pp. 187–212.

* Hanrieder, T. and Kreuder-Sonnen, C. (2014) [‘WHO decides on the exception? Securitization and emergency governance in global health’](https://www.jstor.org/stable/26291745), *Security Dialogue 45(4)*: 331–48.

* Kreuder-Sonnen, C. (2019) [Emergency Powers of International Organizations: Between Normalization and Containment](https://academic.oup.com/book/36875), Oxford: *Oxford University Press*.

* Kreuder-Sonnen, C. (2019) [‘International authority and the emergency problematique: IO empowerment through crises’](https://www.cambridge.org/core/journals/international-theory/article/international-authority-and-the-emergency-problematique-io-empowerment-through-crises/AE4DDC06A436FA707291BC86E5A00FE0), *International Theory* 11(2): 182–210.

<br>

* Rauh, C. and Parizek, M. (2024) [‘Converging on Europe? The European Union in mediatised debates during the COVID-19 and Ukraine shocks’](https://www.tandfonline.com/doi/full/10.1080/13501763.2024.2344849), *Journal of European Public Policy*  31(10): 3036-3065.

* Rauh, C. (2022) [‘Supranational emergency politics? What executives’ public crisis communication may tell us’](https://www.tandfonline.com/doi/full/10.1080/13501763.2021.1916058), *Journal of European Public Policy* 29(6): 966–78.

* Rauh, C. (2021) [‘One agenda-setter or many? The varying success of policy initiatives by individual Directorates-General of the European Commission 1994–2016’](https://journals.sagepub.com/doi/full/10.1177/1465116520961467), *European Union Politics* 22(1): 3–24.

* Rauh, C. and M. Zürn (2020) ['Authority, politicization, and alternative justifications: endogenous legitimation dynamics in global economic governance'](https://www.tandfonline.com/doi/full/10.1080/09692290.2019.1650796) *Review of International Political Economy*, 27(3): 583-611.

* Hartlapp, M., Metz, J., and C. Rauh (2014) ['Which policy for Europe?: Power and Conflict inside the European Commission'](https://global.oup.com/academic/product/which-policy-for-europe-9780199688036?cc=de&lang=en&#), Oxford: *Oxford University Press*.

:::
